# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'SoundVillage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SoundVillage

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'
  pod 'Firebase/Functions', '~> 5.15.0'
  # pod 'Firebase/DynamicLinks', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Storage', '~> 5.15.0'

  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge', # Include this for RN >= 0.47
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', # needed for debugging
      'RCTAnimation',
      'RCTActionSheet',
      'RCTBlob',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTVibration',
      'RCTPushNotification',
      'RCTCameraRoll',
      # Add any other subspecs you want to use in your project
    ]

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  pod 'ReactNativeSearchBar', :path => '../node_modules/react-native-search-bar'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
